# Generated by Django 4.0.6 on 2022-08-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_complete',
        ),
    ]
